### ISSUE TITLE
TypeError: Cannot set property 'error' of undefined at createArchive

### ISSUE THREAD

**Issue by sonn-gamm** [jondashkyle/choo-dat-hypha#1]
Hi,

this might be a dumb error, as I am poking with `node.js` and `choo.js` only for a few times now, and have not yet an idea of how to set things up.

What I do is:

1. `npx create-choo-app <project-directory>`
2. `cd <project-directory> && npm i choo-dat-hypha`
3. I follow your instructions on how to add the new `hypha` module to `choo.js` and make a `content` folder with an `index.txt`, plus one sub-folder with an `index.txt` as well (and some text fields inside each text file).
4. I add `app.use(require('choo-dat-hypha')('/content'))` to `index.js`; I make a new `wrapper.js` file in `/views`, do `npm install xtend` and use the `wrapper.js` module in `views/main.js`

I run `npm start` and get the following error log (running `node v8.7.0`)

```
A critical error occured, forcing Bankai to abort:
npm ERR! code ELIFECYCLE
npm ERR! errno 1t set property 'error' of undefined
npm ERR! tekken@1.0.0 start: `bankai start index.js`n/node_modules/choo-dat-hypha/npm ERR! Exit status 1
npm ERR! ore (/Users/xx/xx/tekken/node_modules/choo-dat-hypha/index.jsnpm ERR! Failed at the tekken@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.nonymous> (/Users/xx/xx/tekken/index.js:8:5)
    at Module._compile (module.js:624:30)
npm ERR! A complete log of this run can be found in:10)
npm ERR!     /Users/xx/.npm/_logs/2018-01-09T22_38_25_092Z-debug.log
~/xx/tekken (master) $ :508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
```

Before I get this error, another error appears

```
TypeError: Cannot set property 'error' of undefined
    at createArchive (/Users/xx/xx/tekken/node_modules/choo-dat-hypha/index.js:56:27)
    at store (/Users/xx/xx/tekken/node_modules/choo-dat-hypha/index.jsscripts:browserify.bundle unsupported type for static module: Property
at expression:

  fs: fs
 while parsing file: /Users/xx/xx/tekken/node_modules/hypha/index.js
Error: unsupported type for static module: Property
at expression:

  fs: fs
 while parsing file: /Users/xx/xx/tekken/node_modules/hypha/index.js
    at traverse (/Users/xx/xx/tekken/node_modules/static-module/index.js:318:34)
    at walk (/Users/xx/xx/tekken/node_modules/static-module/index.js:224:18)
    at walk (/Users/xx/xx/tekken/node_modules/falafel/index.js:49:9)
    at /Users/xx/xx/tekken/node_modules/falafel/index.js:46:17
    at forEach (/Users/xx/xx/tekken/node_modules/foreach/index.js:12:16)
    at walk (/Users/xx/xx/tekken/node_modules/falafel/index.js:34:9)
    at /Users/xx/xx/tekken/node_modules/falafel/index.js:41:25
    at forEach (/Users/xx/xx/tekken/node_modules/foreach/index.js:12:16)
    at /Users/xx/xx/tekken/node_modules/falafel/index.js:39:17
    at forEach (/Users/xx/xx/tekken/node_modules/foreach/index.js:12:16)
```

**Comment by jondashkyle** [comment]
Hey! `choo-dat-hypha` is for running within Beaker Browser. You can see an [example here](
https://github.com/jondashkyle/hypha-beaker/tree/master/site). If you want to use `hypha` outside of Beaker, try using the basic [Hypha module](https://github.com/jondashkyle/hypha) and the [example here](https://github.com/jondashkyle/hypha/tree/master/example).

Depending upon the environment, we read files differently. When running locally on your machine, we must use a Browserify transform to statically inline files. This turns the directory and files into an object, the entirety of which ends up in our bundle.

When running inside Beaker, and if we’d like to dynamically generate the site based off the file system to avoid re-bundling, we must use the Web API to asynchronously read files from the Dat Archive.

This can be a little confusing! I’m still feeling out where to create boundaries between modules, and how to elegantly handle context switching between the http/p2p web.

**Comment by sonn-gamm** [comment]
Thanks for shedding some light, I understand a little better now! 

I think I'll opt for the Beaker browser version, since I want to keep editing the `content/` folder and have updated views without rebundling.
